cluster_name: yolov4

max_workers: 1

provider:
    type: aws
    region: us-west-1

available_node_types:
    4-gpu-node:
        min_workers: 1
        max_workers: 1
        node_config:
            InstanceType: g4dn.12xlarge
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 200
        resources: {}

head_node_type: 4-gpu-node

setup_commands:
    - pip install -U ray[default]@https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - git clone https://github.com/matthewdeng/pytorch-YOLOv4.git; pip install -r pytorch-YOLOv4/requirements.txt
    - ls
    - mkdir aquarium; curl -L "ADD LINK HERE" > roboflow.zip; unzip -o roboflow.zip -d aquarium; rm roboflow.zip
    - mkdir aquarium/images; cp aquarium/train/*.jpg aquarium/images/; cp aquarium/valid/*.jpg aquarium/images/
    - pip install gdown
    - gdown https://drive.google.com/uc?id=1fcbR0bWzYfIEdLJPzOsn4R5mlvR6IQyA
